<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/member.proto

namespace Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>member.GetUserListResponse</code>
 */
class GetUserListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string err = 2;</code>
     */
    protected $err = '';
    /**
     * Generated from protobuf field <code>repeated .member.Member data = 3;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $code
     *     @type string $err
     *     @type \Member\Member[]|\Google\Protobuf\Internal\RepeatedField $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobufs\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string err = 2;</code>
     * @return string
     */
    public function getErr()
    {
        return $this->err;
    }

    /**
     * Generated from protobuf field <code>string err = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErr($var)
    {
        GPBUtil::checkString($var, True);
        $this->err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .member.Member data = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .member.Member data = 3;</code>
     * @param \Member\Member[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Member\Member::class);
        $this->data = $arr;

        return $this;
    }

}

