<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/member.proto

namespace Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>member.GetUserListRequest</code>
 */
class GetUserListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string keyword = 1;</code>
     */
    protected $keyword = '';
    /**
     * Generated from protobuf field <code>int64 page = 2;</code>
     */
    protected $page = 0;
    /**
     * Generated from protobuf field <code>int64 size = 3;</code>
     */
    protected $size = 0;
    /**
     * Generated from protobuf field <code>int64 type = 4;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $keyword
     *     @type int|string $page
     *     @type int|string $size
     *     @type int|string $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobufs\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string keyword = 1;</code>
     * @return string
     */
    public function getKeyword()
    {
        return $this->keyword;
    }

    /**
     * Generated from protobuf field <code>string keyword = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyword($var)
    {
        GPBUtil::checkString($var, True);
        $this->keyword = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 page = 2;</code>
     * @return int|string
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Generated from protobuf field <code>int64 page = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 size = 3;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>int64 size = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 type = 4;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int64 type = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->type = $var;

        return $this;
    }

}

