<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/member.proto

namespace Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>member.GetUserInfoResponse</code>
 */
class GetUserInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string err = 2;</code>
     */
    protected $err = '';
    /**
     * Generated from protobuf field <code>.member.Member info = 3;</code>
     */
    protected $info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $code
     *     @type string $err
     *     @type \Member\Member $info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protobufs\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @return int|string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int64 code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt64($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string err = 2;</code>
     * @return string
     */
    public function getErr()
    {
        return $this->err;
    }

    /**
     * Generated from protobuf field <code>string err = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErr($var)
    {
        GPBUtil::checkString($var, True);
        $this->err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.member.Member info = 3;</code>
     * @return \Member\Member|null
     */
    public function getInfo()
    {
        return isset($this->info) ? $this->info : null;
    }

    public function hasInfo()
    {
        return isset($this->info);
    }

    public function clearInfo()
    {
        unset($this->info);
    }

    /**
     * Generated from protobuf field <code>.member.Member info = 3;</code>
     * @param \Member\Member $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Member\Member::class);
        $this->info = $var;

        return $this;
    }

}

