<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/member.proto

namespace Member;

use UnexpectedValueException;

/**
 * Protobuf type <code>member.MemberSexEnum</code>
 */
class MemberSexEnum
{
    /**
     * Generated from protobuf enum <code>SEX_UNKNOWN = 0;</code>
     */
    const SEX_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>SEX_BOY = 1;</code>
     */
    const SEX_BOY = 1;
    /**
     * Generated from protobuf enum <code>SEX_GIRL = 2;</code>
     */
    const SEX_GIRL = 2;

    private static $valueToName = [
        self::SEX_UNKNOWN => 'SEX_UNKNOWN',
        self::SEX_BOY => 'SEX_BOY',
        self::SEX_GIRL => 'SEX_GIRL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

